"""Contrats de repository (docs/domain-model.md §11) — un Protocol par agrégat.

Ces interfaces ne portent aucune règle métier : uniquement des opérations de
lecture/écriture sur les schémas Pydantic de chaque agrégat. La validation des
transitions, la déduplication applicative, etc. relèvent d'une couche de cas
d'usage à construire ultérieurement.
"""

import uuid
from datetime import datetime
from typing import Protocol

from memory_agent.enums import CategorieSkill, SourceType, StatutCandidature, StatutPost, StatutQualification
from memory_agent.schemas.audit import AuditEvent
from memory_agent.schemas.candidature import Candidature
from memory_agent.schemas.common import Acteur, Tag
from memory_agent.schemas.company import Company
from memory_agent.schemas.contact import Contact
from memory_agent.schemas.document import Document
from memory_agent.schemas.linkedin import LinkedInConversation, LinkedInPost, LinkedInProfile
from memory_agent.schemas.mission import Mission
from memory_agent.schemas.profile import Profile
from memory_agent.schemas.skill import Skill
from memory_agent.schemas.user import User


class UserRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> User | None: ...
    def par_email(self, email: str) -> User | None: ...
    def sauvegarder(self, user: User) -> User: ...


class ProfileRepository(Protocol):
    def get_profil(self, user_id: uuid.UUID) -> Profile | None: ...
    def sauvegarder(self, profil: Profile) -> Profile: ...


class SkillRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Skill | None: ...
    def par_nom_ou_alias(self, libelle: str) -> Skill | None: ...
    def lister(self, categorie: CategorieSkill | None = None) -> list[Skill]: ...
    def sauvegarder(self, skill: Skill) -> Skill: ...


class CompanyRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Company | None: ...
    def par_nom(self, nom: str) -> Company | None: ...
    def sauvegarder(self, company: Company) -> Company: ...


class MissionRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Mission | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[Mission]: ...
    def par_reference_externe(self, user_id: uuid.UUID, reference_externe: str) -> Mission | None: ...
    def par_source(self, user_id: uuid.UUID, source_type: SourceType) -> list[Mission]: ...
    def par_statut_de_qualification(
        self, user_id: uuid.UUID, statut: StatutQualification
    ) -> list[Mission]: ...
    def par_tag(self, user_id: uuid.UUID, tag: Tag) -> list[Mission]: ...
    def sauvegarder(self, mission: Mission) -> Mission: ...


class CandidatureRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Candidature | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[Candidature]: ...
    def par_mission(self, mission_id: uuid.UUID) -> Candidature | None: ...
    def par_statut(self, user_id: uuid.UUID, statut: StatutCandidature) -> list[Candidature]: ...
    def lister_actives(self, user_id: uuid.UUID) -> list[Candidature]: ...
    def sauvegarder(self, candidature: Candidature) -> Candidature: ...


class ContactRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Contact | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[Contact]: ...
    def par_email(self, user_id: uuid.UUID, email: str) -> Contact | None: ...
    def par_reference_externe(self, user_id: uuid.UUID, reference_externe: str) -> Contact | None: ...
    def par_company(self, company_id: uuid.UUID) -> list[Contact]: ...
    def sauvegarder(self, contact: Contact) -> Contact: ...


class DocumentRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> Document | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[Document]: ...
    def par_candidature(self, candidature_id: uuid.UUID) -> list[Document]: ...
    def par_mission(self, mission_id: uuid.UUID) -> list[Document]: ...
    def sauvegarder(self, document: Document) -> Document: ...


class LinkedInProfileRepository(Protocol):
    def get_profile(self, user_id: uuid.UUID) -> LinkedInProfile | None: ...
    def sauvegarder(self, profile: LinkedInProfile) -> LinkedInProfile: ...


class LinkedInPostRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> LinkedInPost | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[LinkedInPost]: ...
    def par_statut(self, user_id: uuid.UUID, statut: StatutPost) -> list[LinkedInPost]: ...
    def sauvegarder(self, post: LinkedInPost) -> LinkedInPost: ...


class LinkedInConversationRepository(Protocol):
    def par_id(self, id: uuid.UUID) -> LinkedInConversation | None: ...
    def par_proprietaire(self, user_id: uuid.UUID) -> list[LinkedInConversation]: ...
    def par_contact(self, contact_id: uuid.UUID) -> list[LinkedInConversation]: ...
    def sauvegarder(self, conversation: LinkedInConversation) -> LinkedInConversation: ...


class AuditEventRepository(Protocol):
    def enregistrer(self, event: AuditEvent) -> AuditEvent: ...
    def par_entite(self, entite_type: str, entite_id: uuid.UUID) -> list[AuditEvent]: ...
    def par_proprietaire(
        self, user_id: uuid.UUID, depuis: datetime | None = None, jusqua: datetime | None = None
    ) -> list[AuditEvent]: ...
    def par_acteur(self, acteur: Acteur) -> list[AuditEvent]: ...
