"""schema initiale memory-agent

Revision ID: 1e85de3e3cf1
Revises: 
Create Date: 2026-07-12 21:13:07.362227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1e85de3e3cf1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('secteur', sa.String(length=150), nullable=True),
    sa.Column('taille', sa.String(length=50), nullable=True),
    sa.Column('site_web', sa.String(length=500), nullable=True),
    sa.Column('ville', sa.String(length=150), nullable=True),
    sa.Column('pays', sa.String(length=150), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_nom'), 'companies', ['nom'], unique=True)
    op.create_table('skills',
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('categorie', sa.Enum('LANGAGE', 'FRAMEWORK', 'CLOUD', 'METHODE', 'SOFT_SKILL', 'AUTRE', name='categorieskill', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_nom'), 'skills', ['nom'], unique=True)
    op.create_table('tags',
    sa.Column('libelle', sa.String(length=100), nullable=False),
    sa.Column('categorie', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('libelle', 'categorie', name='uq_tag_libelle_categorie')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('statut_compte', sa.Enum('ACTIF', 'DESACTIVE', name='statutcompte', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_events',
    sa.Column('horodatage', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('type_evenement', sa.String(length=100), nullable=False),
    sa.Column('entite_type', sa.String(length=50), nullable=False),
    sa.Column('entite_id', sa.Uuid(), nullable=False),
    sa.Column('acteur_type', sa.Enum('UTILISATEUR', 'AGENT', name='acteurtype', native_enum=False, length=20), nullable=False),
    sa.Column('acteur_identifiant', sa.String(length=150), nullable=False),
    sa.Column('proprietaire_user_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['proprietaire_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_events_entite', 'audit_events', ['entite_type', 'entite_id'], unique=False)
    op.create_index(op.f('ix_audit_events_proprietaire_user_id'), 'audit_events', ['proprietaire_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_type_evenement'), 'audit_events', ['type_evenement'], unique=False)
    op.create_table('contacts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=50), nullable=True),
    sa.Column('url_linkedin', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.Enum('LINKEDIN', 'PLATEFORME_FREELANCE', 'RESEAU_PERSONNEL', 'COOPTATION', 'CANDIDATURE_SPONTANEE', 'SAISIE_MANUELLE', 'GENERATION_AGENT', name='sourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('source_reference_externe', sa.String(length=1000), nullable=True),
    sa.Column('source_agent_responsable', sa.String(length=100), nullable=True),
    sa.Column('source_importe_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_user_id'), 'contacts', ['user_id'], unique=False)
    op.create_index('uq_contact_user_email', 'contacts', ['user_id', 'email'], unique=True, sqlite_where=sa.text('email IS NOT NULL'), postgresql_where=sa.text('email IS NOT NULL'))
    op.create_index('uq_contact_user_reference_externe', 'contacts', ['user_id', 'source_reference_externe'], unique=True, sqlite_where=sa.text('source_reference_externe IS NOT NULL'), postgresql_where=sa.text('source_reference_externe IS NOT NULL'))
    op.create_index('uq_contact_user_url_linkedin', 'contacts', ['user_id', 'url_linkedin'], unique=True, sqlite_where=sa.text('url_linkedin IS NOT NULL'), postgresql_where=sa.text('url_linkedin IS NOT NULL'))
    op.create_table('entity_tags',
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('MISSION', 'CANDIDATURE', 'CONTACT', 'COMPANY', 'DOCUMENT', 'LINKEDIN_POST', 'LINKEDIN_CONVERSATION', name='taggableentitytype', native_enum=False, length=30), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_entity_tag_unique')
    )
    op.create_index('ix_entity_tags_entity', 'entity_tags', ['entity_type', 'entity_id'], unique=False)
    op.create_table('linkedin_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('titre_affiche', sa.String(length=255), nullable=True),
    sa.Column('resume', sa.String(length=4000), nullable=True),
    sa.Column('derniere_synchronisation', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('missions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=8000), nullable=True),
    sa.Column('tjm_min', sa.Float(), nullable=True),
    sa.Column('tjm_max', sa.Float(), nullable=True),
    sa.Column('tjm_devise', sa.String(length=10), nullable=False),
    sa.Column('tjm_unite', sa.String(length=10), nullable=False),
    sa.Column('statut_qualification', sa.Enum('NON_QUALIFIEE', 'QUALIFIEE', 'ECARTEE', name='statutqualification', native_enum=False, length=20), nullable=False),
    sa.Column('score_qualification', sa.Float(), nullable=True),
    sa.Column('motif_qualification', sa.String(length=2000), nullable=True),
    sa.Column('source_type', sa.Enum('LINKEDIN', 'PLATEFORME_FREELANCE', 'RESEAU_PERSONNEL', 'COOPTATION', 'CANDIDATURE_SPONTANEE', 'SAISIE_MANUELLE', 'GENERATION_AGENT', name='sourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('source_reference_externe', sa.String(length=1000), nullable=True),
    sa.Column('source_agent_responsable', sa.String(length=100), nullable=True),
    sa.Column('source_importe_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_user_id'), 'missions', ['user_id'], unique=False)
    op.create_index('uq_mission_user_reference_externe', 'missions', ['user_id', 'source_reference_externe'], unique=True, sqlite_where=sa.text('source_reference_externe IS NOT NULL'), postgresql_where=sa.text('source_reference_externe IS NOT NULL'))
    op.create_table('profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('resume', sa.String(length=4000), nullable=True),
    sa.Column('tjm_min', sa.Float(), nullable=True),
    sa.Column('tjm_max', sa.Float(), nullable=True),
    sa.Column('tjm_devise', sa.String(length=10), nullable=False),
    sa.Column('tjm_unite', sa.String(length=10), nullable=False),
    sa.Column('remote_preference', sa.Enum('TOTAL', 'PARTIEL', 'NON', name='remotepreference', native_enum=False, length=10), nullable=True),
    sa.Column('ville_base', sa.String(length=150), nullable=True),
    sa.Column('perimetre_deplacement_km', sa.Integer(), nullable=True),
    sa.Column('disponibilite_debut', sa.DateTime(), nullable=True),
    sa.Column('disponibilite_fin', sa.DateTime(), nullable=True),
    sa.Column('criteres_tjm_min', sa.Float(), nullable=True),
    sa.Column('criteres_remote_requis', sa.Boolean(), nullable=True),
    sa.Column('criteres_types_contrat_acceptes', sa.JSON(), nullable=True),
    sa.Column('criteres_secteurs_exclus', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('skill_aliases',
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('skill_id', 'libelle', name='uq_skill_alias')
    )
    op.create_index(op.f('ix_skill_aliases_libelle'), 'skill_aliases', ['libelle'], unique=True)
    op.create_table('documents',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=True),
    sa.Column('previous_version_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('CV', 'LETTRE_MOTIVATION', 'PORTFOLIO', 'AUTRE', name='typedocument', native_enum=False, length=30), nullable=False),
    sa.Column('version_label', sa.String(length=50), nullable=True),
    sa.Column('reference_fichier', sa.String(length=1000), nullable=False),
    sa.Column('source_type', sa.Enum('LINKEDIN', 'PLATEFORME_FREELANCE', 'RESEAU_PERSONNEL', 'COOPTATION', 'CANDIDATURE_SPONTANEE', 'SAISIE_MANUELLE', 'GENERATION_AGENT', name='sourcetype', native_enum=False, length=30), nullable=False),
    sa.Column('source_reference_externe', sa.String(length=1000), nullable=True),
    sa.Column('source_agent_responsable', sa.String(length=100), nullable=True),
    sa.Column('source_importe_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    op.create_table('experiences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=True),
    sa.Column('entreprise_nom', sa.String(length=255), nullable=True),
    sa.Column('intitule', sa.String(length=255), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=4000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linkedin_conversations',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('ACTIVE', 'SANS_REPONSE', 'CLOSE', name='statutconversation', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_conversations_user_id'), 'linkedin_conversations', ['user_id'], unique=False)
    op.create_table('linkedin_posts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('linkedin_profile_id', sa.Uuid(), nullable=False),
    sa.Column('contenu', sa.String(length=8000), nullable=False),
    sa.Column('statut', sa.Enum('BROUILLON', 'PLANIFIE', 'PUBLIE', 'ARCHIVE', name='statutpost', native_enum=False, length=20), nullable=False),
    sa.Column('date_planifiee', sa.DateTime(), nullable=True),
    sa.Column('date_publication', sa.DateTime(), nullable=True),
    sa.Column('metriques_vues', sa.Integer(), nullable=True),
    sa.Column('metriques_reactions', sa.Integer(), nullable=True),
    sa.Column('metriques_commentaires', sa.Integer(), nullable=True),
    sa.Column('metriques_mesurees_le', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['linkedin_profile_id'], ['linkedin_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linkedin_posts_user_id'), 'linkedin_posts', ['user_id'], unique=False)
    op.create_table('mission_competences_requises',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('niveau_requis', sa.Enum('JUNIOR', 'CONFIRME', 'EXPERT', name='niveaucompetence', native_enum=False, length=20), nullable=True),
    sa.Column('obligatoire', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'skill_id', name='uq_mission_competence')
    )
    op.create_table('mission_contacts',
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id', 'contact_id', name='uq_mission_contact')
    )
    op.create_table('profile_competences',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('niveau', sa.Enum('JUNIOR', 'CONFIRME', 'EXPERT', name='niveaucompetence', native_enum=False, length=20), nullable=False),
    sa.Column('annees_experience', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', name='uq_profile_competence')
    )
    op.create_table('profile_criteria_skills',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('RECHERCHE', 'EXCLU', name='typecritereskill', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'skill_id', 'type', name='uq_profile_criteria_skill')
    )
    op.create_table('candidatures',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('mission_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=True),
    sa.Column('statut', sa.Enum('REPEREE', 'POSTULEE', 'ENTRETIEN_PLANIFIE', 'ENTRETIEN_REALISE', 'OFFRE_RECUE', 'ACCEPTEE', 'REFUSEE', 'SANS_REPONSE', 'ABANDONNEE', name='statutcandidature', native_enum=False, length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mission_id')
    )
    op.create_index(op.f('ix_candidatures_user_id'), 'candidatures', ['user_id'], unique=False)
    op.create_table('experience_skills',
    sa.Column('experience_id', sa.Uuid(), nullable=False),
    sa.Column('skill_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['experience_id'], ['experiences.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('experience_id', 'skill_id', name='uq_experience_skill')
    )
    op.create_table('linkedin_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('expediteur', sa.Enum('UTILISATEUR', 'CONTACT', name='expediteurmessage', native_enum=False, length=20), nullable=False),
    sa.Column('contenu', sa.String(length=4000), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['linkedin_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidature_contacts',
    sa.Column('candidature_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidature_id', 'contact_id', name='uq_candidature_contact')
    )
    op.create_table('candidature_statut_historique',
    sa.Column('candidature_id', sa.Uuid(), nullable=False),
    sa.Column('statut_precedent', sa.Enum('REPEREE', 'POSTULEE', 'ENTRETIEN_PLANIFIE', 'ENTRETIEN_REALISE', 'OFFRE_RECUE', 'ACCEPTEE', 'REFUSEE', 'SANS_REPONSE', 'ABANDONNEE', name='statutcandidature', native_enum=False, length=30), nullable=True),
    sa.Column('statut_nouveau', sa.Enum('REPEREE', 'POSTULEE', 'ENTRETIEN_PLANIFIE', 'ENTRETIEN_REALISE', 'OFFRE_RECUE', 'ACCEPTEE', 'REFUSEE', 'SANS_REPONSE', 'ABANDONNEE', name='statutcandidature', native_enum=False, length=30), nullable=False),
    sa.Column('horodatage', sa.DateTime(), nullable=False),
    sa.Column('motif', sa.String(length=2000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entretiens',
    sa.Column('candidature_id', sa.Uuid(), nullable=False),
    sa.Column('statut', sa.Enum('PLANIFIE', 'REALISE', 'ANNULE', name='statutentretien', native_enum=False, length=20), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('date_prevue', sa.DateTime(), nullable=True),
    sa.Column('date_realisee', sa.DateTime(), nullable=True),
    sa.Column('preparation', sa.String(length=8000), nullable=True),
    sa.Column('compte_rendu', sa.String(length=8000), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidature_id'], ['candidatures.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entretiens')
    op.drop_table('candidature_statut_historique')
    op.drop_table('candidature_contacts')
    op.drop_table('linkedin_messages')
    op.drop_table('experience_skills')
    op.drop_index(op.f('ix_candidatures_user_id'), table_name='candidatures')
    op.drop_table('candidatures')
    op.drop_table('profile_criteria_skills')
    op.drop_table('profile_competences')
    op.drop_table('mission_contacts')
    op.drop_table('mission_competences_requises')
    op.drop_index(op.f('ix_linkedin_posts_user_id'), table_name='linkedin_posts')
    op.drop_table('linkedin_posts')
    op.drop_index(op.f('ix_linkedin_conversations_user_id'), table_name='linkedin_conversations')
    op.drop_table('linkedin_conversations')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_skill_aliases_libelle'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_table('profiles')
    op.drop_index('uq_mission_user_reference_externe', table_name='missions', sqlite_where=sa.text('source_reference_externe IS NOT NULL'), postgresql_where=sa.text('source_reference_externe IS NOT NULL'))
    op.drop_index(op.f('ix_missions_user_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_table('linkedin_profiles')
    op.drop_index('ix_entity_tags_entity', table_name='entity_tags')
    op.drop_table('entity_tags')
    op.drop_index('uq_contact_user_url_linkedin', table_name='contacts', sqlite_where=sa.text('url_linkedin IS NOT NULL'), postgresql_where=sa.text('url_linkedin IS NOT NULL'))
    op.drop_index('uq_contact_user_reference_externe', table_name='contacts', sqlite_where=sa.text('source_reference_externe IS NOT NULL'), postgresql_where=sa.text('source_reference_externe IS NOT NULL'))
    op.drop_index('uq_contact_user_email', table_name='contacts', sqlite_where=sa.text('email IS NOT NULL'), postgresql_where=sa.text('email IS NOT NULL'))
    op.drop_index(op.f('ix_contacts_user_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_audit_events_type_evenement'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_proprietaire_user_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_entite', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('tags')
    op.drop_index(op.f('ix_skills_nom'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_companies_nom'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
